//! Wire types for the timestamp oracle.
//!
//! Generated by `tonic-prost-build` from `proto/tsoracle/v1/tso.proto`.
//! This crate is the stable wire contract shared between `tsoracle-server`
//! and `tsoracle-client`; breaking changes are enforced via `buf breaking`
//! in CI (see `CONTRIBUTING.md`).

#![allow(clippy::all)]

pub mod v1 {
    tonic::include_proto!("tsoracle.v1");
}

#[cfg(test)]
mod tests {
    use super::v1::*;

    #[test]
    fn message_types_exist() {
        let _ = GetTsRequest { count: 1 };
        let _ = GetTsResponse {
            physical_ms: 0,
            logical_start: 0,
            count: 0,
            epoch: 0,
        };
        let _ = LeaderHint {
            leader_endpoint: Some("127.0.0.1:50551".into()),
            leader_epoch: Some(1),
        };
    }
}
