[package]
name         = "tsoracle-client"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
description  = "gRPC client driver for the timestamp oracle."
documentation = "https://docs.rs/tsoracle-client"
keywords      = ["tsoracle", "grpc", "client", "timestamp", "oracle"]
categories    = ["network-programming", "database", "api-bindings"]

[features]
default    = ["tls-rustls"]
tls-rustls = ["tonic/tls-aws-lc"]
tls-native = ["tonic/tls-native-roots"]
tracing    = ["dep:tracing"]
bt         = ["tsoracle-core/bt"]

[package.metadata.docs.rs]
features       = ["tls-rustls", "tracing"]
rustdoc-args   = ["--cfg", "docsrs"]

[dependencies]
async-trait    = { workspace = true }
futures        = { workspace = true }
parking_lot    = { workspace = true }
prost          = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }
tonic          = { workspace = true }
tracing        = { workspace = true, optional = true }
tsoracle-core  = { path = "../tsoracle-core", version = "0.1.1" }
tsoracle-proto = { path = "../tsoracle-proto", version = "0.1.1" }

[dev-dependencies]
tokio    = { workspace = true, features = ["test-util"] }
proptest = { workspace = true }
