{{- if eq .Values.driver "file" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tsoracle.name" . }}-data
  labels:
    {{- include "tsoracle.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
