{{ include "tsoracle.validate" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsoracle.name" . }}
  labels:
    {{- include "tsoracle.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ .Values.ports.client }}
      targetPort: tso
  selector:
    app.kubernetes.io/name: tsoracle
    app.kubernetes.io/instance: {{ .Release.Name }}
