apiVersion: v1
kind: Service
metadata:
  name: tsoracle-peer
  labels:
    app.kubernetes.io/name: tsoracle
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tsoracle
  publishNotReadyAddresses: true
  ports:
    - name: raft
      port: 5100
      targetPort: raft
    - name: tso
      port: 5051
      targetPort: tso
---
apiVersion: v1
kind: Service
metadata:
  name: tsoracle
  labels:
    app.kubernetes.io/name: tsoracle
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tsoracle
  ports:
    - name: tso
      port: 5051
      targetPort: tso
