[package]
name                   = "example-paxos-standalone"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description            = "tsoracle example: HA via OmniPaxos, 3-node multi-process cluster (uses tsoracle-driver-paxos)"
publish                = false

[[bin]]
name = "paxos-standalone"
path = "src/main.rs"

[features]
default    = ["reflection"]
reflection = ["tsoracle-server/reflection"]

[dependencies]
tsoracle-server     = { path = "../../crates/tsoracle-server", version = "3.2.2" }
tsoracle-standalone = { path = "../../crates/tsoracle-standalone", version = "1.4.1", default-features = false, features = ["paxos"] }
tokio               = { workspace = true, features = ["signal", "macros", "rt-multi-thread"] }
clap                = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
anyhow              = { workspace = true }
