[package]
name                   = "example-openraft-standalone"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description            = "tsoracle example: HA via openraft, 3-node multi-process cluster (uses tsoracle-driver-openraft)"
publish                = false

[[bin]]
name = "openraft-standalone"
path = "src/main.rs"

[features]
default    = ["reflection"]
reflection = ["tsoracle-server/reflection"]

[dependencies]
tsoracle-server     = { path = "../../crates/tsoracle-server", version = "3.0.1" }
tsoracle-standalone = { path = "../../crates/tsoracle-standalone", version = "1.1.2", default-features = false, features = ["openraft"] }
tokio               = { workspace = true, features = ["signal", "macros", "rt-multi-thread"] }
clap                = { workspace = true }
tracing             = { workspace = true }
tracing-subscriber  = { workspace = true }
anyhow              = { workspace = true }

[dev-dependencies]
tokio    = { workspace = true, features = ["process", "net", "time", "macros", "rt-multi-thread"] }
tempfile = { workspace = true }
