[package]
name                   = "example-paxos-embedded"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
description            = "tsoracle example: embed an OmniPaxos cluster + tsoracle-server in your own binary"
publish                = false

[[bin]]
name = "paxos-embedded"
path = "src/main.rs"

[dependencies]
tsoracle-core          = { path = "../../crates/tsoracle-core", version = "0.2.0" }
tsoracle-consensus     = { path = "../../crates/tsoracle-consensus", version = "0.1.5" }
tsoracle-server        = { path = "../../crates/tsoracle-server", version = "0.2.1" }
tsoracle-driver-paxos  = { path = "../../crates/tsoracle-driver-paxos", version = "0.2.0" }
tsoracle-paxos-toolkit = { path = "../../crates/tsoracle-paxos-toolkit", version = "0.2.0", default-features = false, features = ["test-fakes"] }

omnipaxos          = { workspace = true, features = ["serde"] }
async-trait        = { workspace = true }
tokio              = { workspace = true, features = ["signal"] }
parking_lot        = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow             = { workspace = true }
